<!DOCTYPE html>
<html lang="en-us">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.8.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Ladislas Nalborczyk">

  
  
  
    
  
  <meta name="description" content="What is the difference between the errors and the residuals? What does it mean for a model to *predict* something? What is a link function? In the current post, we use four R functions (viz., the `predict`, `fitted`, `residuals` and `simulate` functions) to illustrate the mechanisms and assumptions of the generalised linear model.">

  
  <link rel="alternate" hreflang="en-us" href="http://www.barelysignificant.com/post/glm/">

  


  
  
  
  <meta name="theme-color" content="rgb(0,51,102)">
  

  
  
  
  <script src="/js/mathjax-config.js"></script>
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" integrity="sha256-4w9DunooKSr3MFXHXWyFER38WmPdm361bQS/2KUWZbU=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha256-Vzbj7sDDS/woiFS3uNKo8eIuni59rjyNGtXfstRzStA=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/github.min.css" crossorigin="anonymous" title="hl-light">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/github.min.css" crossorigin="anonymous" title="hl-dark" disabled>
      
    

    

    

    
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.1.2/lazysizes.min.js" integrity="sha256-Md1qLToewPeKjfAHU1zyPwOutccPAm5tahnaw7Osw0A=" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" integrity="" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    

  

  
  
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700%7CMontserrat:400,400italic,700%7CRoboto+Mono&display=swap">
  

  
  
  
  
  <link rel="stylesheet" href="/css/academic.css">

  





<script async src="https://www.googletagmanager.com/gtag/js?id=UA-86650162-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];

  function gtag() {
      dataLayer.push(arguments);
  }

  function trackOutboundLink(url, target) {
    gtag('event', 'click', {
         'event_category': 'outbound',
         'event_label': url,
         'transport_type': 'beacon',
         'event_callback': function () {
           if (target !== '_blank') {
             document.location = url;
           }
         }
    });
    console.debug("Outbound link clicked: " + url);
  }

  function onClickCallback(event) {
    if ((event.target.tagName !== 'A') || (event.target.host === window.location.host)) {
      return;
    }
    trackOutboundLink(event.target, event.target.getAttribute('target'));  
  }

  gtag('js', new Date());
  gtag('config', 'UA-86650162-1', { 'anonymize_ip': true });

  
  document.addEventListener('click', onClickCallback, false);
</script>


  


  
  

  

  <link rel="manifest" href="/index.webmanifest">
  <link rel="icon" type="image/png" href="/images/icon_hu0b7a4cb9992c9ac0e91bd28ffd38dd00_9727_32x32_fill_lanczos_center_2.png">
  <link rel="apple-touch-icon" type="image/png" href="/images/icon_hu0b7a4cb9992c9ac0e91bd28ffd38dd00_9727_192x192_fill_lanczos_center_2.png">

  <link rel="canonical" href="http://www.barelysignificant.com/post/glm/">

  
  
  
  
  
  
  
    
  
  
  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="twitter:site" content="@lnalborczyk">
  <meta property="twitter:creator" content="@lnalborczyk">
  
  <meta property="og:site_name" content="BARELY SIGNIFICANT">
  <meta property="og:url" content="http://www.barelysignificant.com/post/glm/">
  <meta property="og:title" content="Using R to make sense of the generalised linear model | BARELY SIGNIFICANT">
  <meta property="og:description" content="What is the difference between the errors and the residuals? What does it mean for a model to *predict* something? What is a link function? In the current post, we use four R functions (viz., the `predict`, `fitted`, `residuals` and `simulate` functions) to illustrate the mechanisms and assumptions of the generalised linear model."><meta property="og:image" content="http://www.barelysignificant.com/img/icon.png">
  <meta property="twitter:image" content="http://www.barelysignificant.com/img/icon.png"><meta property="og:locale" content="en-us">
  
    
      <meta property="article:published_time" content="2018-01-15T00:00:00&#43;00:00">
    
    <meta property="article:modified_time" content="2018-01-15T00:00:00&#43;00:00">
  

  


    






  




<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "http://www.barelysignificant.com/post/glm/"
  },
  "headline": "Using R to make sense of the generalised linear model",
  
  "datePublished": "2018-01-15T00:00:00Z",
  "dateModified": "2018-01-15T00:00:00Z",
  
  "author": {
    "@type": "Person",
    "name": "Ladislas Nalborczyk"
  },
  
  "publisher": {
    "@type": "Organization",
    "name": "BARELY SIGNIFICANT",
    "logo": {
      "@type": "ImageObject",
      "url": "http://www.barelysignificant.com/images/icon_hu0b7a4cb9992c9ac0e91bd28ffd38dd00_9727_192x192_fill_lanczos_center_2.png"
    }
  },
  "description": "What is the difference between the errors and the residuals? What does it mean for a model to *predict* something? What is a link function? In the current post, we use four R functions (viz., the `predict`, `fitted`, `residuals` and `simulate` functions) to illustrate the mechanisms and assumptions of the generalised linear model."
}
</script>

  

  


  
  
  
  
  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.1/cookieconsent.min.js" integrity="sha256-5VhCqFam2Cn+yjw61zbBNrbHVJ6SRydPeKopYlngbiQ=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.1/cookieconsent.min.css" integrity="sha256-zQ0LblD/Af8vOppw18+2anxsuaz3pWYyVWi+bTvTH8Q=" crossorigin="anonymous">
  
  <script>
  window.addEventListener("load", function(){
    window.cookieconsent.initialise({
      "palette": {
        "popup": {
          "background": "rgb(0,51,102)",
          "text": "#fff"
        },
        "button": {
          "background": "#fff",
          "text": "rgb(0,51,102)"
        }
      },
      "theme": "classic",
      "content": {
        "message": "This website uses cookies to ensure you get the best experience on our website.",
        "dismiss": "Got it!",
        "link": "Learn more",
        "href": "https://www.cookiesandyou.com"
      }
    })});
  </script>



  





  <title>Using R to make sense of the generalised linear model | BARELY SIGNIFICANT</title>

</head>

<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" >

  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


  







<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/">BARELY SIGNIFICANT</a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/">BARELY SIGNIFICANT</a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-start" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#about"><span>HOME</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#publications"><span>PUBLICATIONS</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#talks"><span>TALKS</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#posts"><span>BLOG</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/pdf/cv.pdf"><span>CV</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#teaching"><span>TEACHING</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#contact"><span>CONTACT</span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">
      
      <li class="nav-item">
        <a class="nav-link js-search" href="#"><i class="fas fa-search" aria-hidden="true"></i></a>
      </li>
      

      

      

    </ul>

  </div>
</nav>


  <article class="article">

  












  

  
  
  
<div class="article-container pt-3">
  <h1>Using R to make sense of the generalised linear model</h1>

  

  
    


<div class="article-metadata">

  
  

  
  <span class="article-date">
    
    
      
    
    Jan 15, 2018
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    16 min read
  </span>
  

  
  
  
  <span class="middot-divider"></span>
  <a href="/post/glm/#disqus_thread"></a>
  

  
  

</div>

    














  
</div>



  <div class="article-container">

    <div class="article-style">
      
<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="statistical-models" class="section level2">
<h2>Statistical models</h2>
<p>Modern science rests on several foundational pillars. Among these is the ability to construct sufficiently solid theoretical abstractions that are able to explain concrete observable aspects of the world. Once the applicability range of a theoretical model has been defined, it is usually compared to another model that is similar in its goal (i.e., another model that aims to explain similar aspects of the world). However, we rarely directly compare theoretical models. Instead, we are brought to compare statistical models that aim to represent theories.</p>
<p>According to Rouder, Morey, &amp; Wagenmakers (2016), “Models are devices that connect theories to data. A model is an instantiation of a theory as a set of probabilistic statements”. One common and convenient example of such instantiation is the linear model, which –in its general form– allows to predict parameter(s) of a distribution, which is supposed to reflect the distribution from which the observed data is issued (the data generation process).</p>
<p>But what does it mean for a model to <em>predict</em> something? In the current post, I focus on four R functions (the <code>predict</code>, <code>fitted</code>, <code>residuals</code> and <code>simulate</code> functions), exploring the similarities and differences between these functions, to illustrate the mechanisms and assumptions of the generalised linear model.</p>
<p>The usual linear model is of the following form.</p>
<p><span class="math display">\[
\begin{aligned}
y_{i} &amp;\sim \mathrm{Normal}(\mu_{i}, \sigma) \\
\mu_{i} &amp;= \alpha + \beta \cdot \text{x}_{i} \\
\end{aligned}
\]</span></p>
<p>Where, in Bayesian terms, the first line of the model corresponds to the <em>likelihood</em> of the model, which is the assumption made about the data generation process. We make the assumption that the outcomes <span class="math inline">\(y_{i}\)</span> are normally distributed around a mean <span class="math inline">\(\mu_{i}\)</span> with some error <span class="math inline">\(\sigma\)</span>. This is equivalent to say that the errors are normally distributed around <span class="math inline">\(0\)</span>.</p>
<p>Of course, the distributional assumption is not restricted to be Gaussian, and can be adapted to whatever distribution that makes sense in consideration of the data at hand. The linear aspect of the linear model actually refers to the second line of the above description, in which one tries to predict parameters of the distribution (e.g., <span class="math inline">\(\mu_{i}\)</span> or <span class="math inline">\(\sigma\)</span>) by a <em>linear combination</em> of some predictor variable(s). Generalising to other distributions, the generalised linear model can be rewritten as:</p>
<p><span class="math display">\[
\begin{aligned}
y_{i} &amp;\sim \mathrm{D}(f(\eta_{i}), \theta) \\
\eta &amp;= \mathbf{X} \beta \\
\end{aligned}
\]</span></p>
<p>Where the response <span class="math inline">\(y_{i}\)</span> is <strong>predicted</strong> through the linear combination <span class="math inline">\(\eta\)</span> of predictors transformed by the inverse link function <span class="math inline">\(f\)</span>, assuming a certain distribution <span class="math inline">\(D\)</span> for <span class="math inline">\(y\)</span> (also called the <em>family</em>), and family-specific parameters <span class="math inline">\(\theta\)</span> (Bürkner, 2017).</p>
<p>Below, we illustrate a simple Gaussian linear model using the <code>Howell1</code> dataset from the <code>rethinking</code> package (McElreath, 2016), which contains data about 544 individuals, including height (centimetres), weight (kilograms), age (years) and gender (0 indicating female and 1 indicating male).</p>
<pre class="r"><code>library(rethinking)
library(tidyverse)
library(ggExtra)

data(Howell1)
d &lt;- Howell1 %&gt;% filter(age &gt;= 18)

p &lt;- d %&gt;%
  ggplot(aes(x = weight, y = height) ) +
  geom_point(pch = 21, color = &quot;white&quot;, fill = &quot;black&quot;, size = 2, alpha = 0.8) +
  geom_smooth(method = &quot;lm&quot;, colour = &quot;black&quot;) +
  theme_bw(base_size = 12)

ggMarginal(p, type = &quot;histogram&quot;)</code></pre>
<p><img src="/post/2018-01-20-glm_files/figure-html/marginal-plot-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>A quick visual exploration of the dataset reveals a positive relationship between height and weight. The above plotted regression line corresponds to the following model, where we assume a normal likelihood:</p>
<p><span class="math display">\[
\begin{aligned}
\text{height}_{i} &amp;\sim \mathrm{Normal}(\mu_{i}, \sigma) \\
\mu_{i} &amp;= \alpha + \beta \cdot \text{weight}_{i} \\
\end{aligned}
\]</span></p>
<p>This model can be fitted easily in <code>R</code> with the following syntax.</p>
<pre class="r"><code>(mod1 &lt;- lm(height ~ weight, data = d) )</code></pre>
<pre><code>## 
## Call:
## lm(formula = height ~ weight, data = d)
## 
## Coefficients:
## (Intercept)       weight  
##     113.879        0.905</code></pre>
<p>The intercept (113.879) represents the predicted height when weight is at 0 (which makes no much sense in our case), whereas the slope (0.905) represents the change in height when weight increases by one unit (i.e., one kilogram).</p>
</div>
<div id="prediction-is-key-predict-and-fitted" class="section level2">
<h2>Prediction is key: <code>predict</code> and <code>fitted</code></h2>
<p>The main advantage of the previous model is that it allows to make predictions for any value of <span class="math inline">\(\text{weight}\)</span>. In <code>R</code>, this is done using the aptly named <code>predict</code> function. For instance, we can ask our model what is the expected height for an individual of weight 43, which is equal to <span class="math inline">\(\alpha + \beta \cdot 43\)</span>.</p>
<pre class="r"><code>wght &lt;- 43

d %&gt;%
  ggplot(aes(x = weight, y = height) ) +
  geom_line(aes(y = predict(mod1) ), size = 1) +
  geom_point(size = 2, alpha = 0.2) +
  geom_segment(
    x = wght, xend = wght,
    y = 0, yend = predict(mod1, newdata = data.frame(weight = wght) ),
    linetype = 2, lwd = 0.5
    ) +
  geom_segment(
    x = 0, xend = wght,
    y = predict(mod1, newdata = data.frame(weight = wght) ),
    yend = predict(mod1, newdata = data.frame(weight = wght) ),
    linetype = 2, lwd = 0.5
    ) +
  theme_bw(base_size = 12)</code></pre>
<p><img src="/post/2018-01-20-glm_files/figure-html/predict-example-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Implementing the function <code>predict</code> by hand is quite easy and will allow us to better understand how it works. This function is actually simply retrieving parameters of the fitted model (in our case, the intercept and the slope) to make predictions about the outcome variable, given some values of the predictor(s). In other words, it corresponds to the second line of our model.</p>
<pre class="r"><code>d &lt;- d %&gt;%
  mutate(
    pred_mod1 = predict(mod1),
    pred_mod1_2 = coef(mod1)[1] + coef(mod1)[2] * weight
    )

head(d)</code></pre>
<pre><code>##    height   weight age male pred_mod1 pred_mod1_2
## 1 151.765 47.82561  63    1  157.1630    157.1630
## 2 139.700 36.48581  63    0  146.9001    146.9001
## 3 136.525 31.86484  65    0  142.7180    142.7180
## 4 156.845 53.04191  41    1  161.8839    161.8839
## 5 145.415 41.27687  51    0  151.2362    151.2362
## 6 163.830 62.99259  35    1  170.8895    170.8895</code></pre>
<p>We could also be interested in predicting the height of individuals with other weights that the weights we observed (e.g., weights between 80 and 100 kgs). Below we simulate new data from our model (i.e., we simulate heights) and predictions for this new set of data (i.e., the <span class="math inline">\(\mu_{i}\)</span>).</p>
<pre class="r"><code># generating weights from 80 to 100 kgs
data.frame(weight = 80:100) %&gt;%
  # retrieving mod1 predictions
  mutate(pred = predict(mod1, newdata = .) ) %&gt;%
  # simulating data from our model, taking into account sigma
  mutate(sim =  pred + rnorm(length(weight), 0, sd(residuals(mod1) ) ) ) %&gt;%
  # or using sigma(mod1) instead of sd(residuals(mod1) ), as suggested
  # by Tristan Mahr (https://www.tjmahr.com)
  mutate(sim =  pred + rnorm(length(weight), 0, sigma(mod1) ) ) %&gt;%
  # plotting these predictions
  ggplot(aes(x = weight, y = pred) ) +
  geom_line(size = 1) +
  geom_point(aes(x = weight, y = sim), size = 2) +
  geom_segment(
      aes(xend = weight, yend = sim),
      size = 0.5, alpha = 0.5, lineend = &quot;round&quot;
      ) +
  theme_bw(base_size = 12)</code></pre>
<p><img src="/post/2018-01-20-glm_files/figure-html/pred-simulations-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Where the vertical lines represent deviations from the predicted values. OK, so we’ve seen the the <code>predict</code> function simply uses the linear model to make predictions about the <span class="math inline">\(\mu_{i}\)</span>.</p>
<p>You might know that there exists a similar function, the <code>fitted</code> function, which allows to extract fitted values of a model.</p>
<pre class="r"><code>d &lt;- d %&gt;% mutate(fitted_mod1 = fitted(mod1) )
head(d)</code></pre>
<pre><code>##    height   weight age male pred_mod1 pred_mod1_2 fitted_mod1
## 1 151.765 47.82561  63    1  157.1630    157.1630    157.1630
## 2 139.700 36.48581  63    0  146.9001    146.9001    146.9001
## 3 136.525 31.86484  65    0  142.7180    142.7180    142.7180
## 4 156.845 53.04191  41    1  161.8839    161.8839    161.8839
## 5 145.415 41.27687  51    0  151.2362    151.2362    151.2362
## 6 163.830 62.99259  35    1  170.8895    170.8895    170.8895</code></pre>
<p>Surprisingly, the <code>predict</code> and <code>fitted</code> functions seem to do the exact same thing (at least their results are the same)… but do they? To answer this question, let’s ask another one.</p>
</div>
<div id="link-function-toward-glms" class="section level2">
<h2>Link function, toward GLMs</h2>
<p>Can we predict gender by individual height? The usual way to answer this kind of question is through a <em>logistic regression</em> model (or logit model). Logistic regression is used to model binary outcome variables, using the linear regression framework. In the logit model, the <em>log-odds</em> of the outcome <span class="math inline">\(p_{i}\)</span> are modelled as a linear combination of the predictor variables:</p>
<p><span class="math display">\[
logit(p_{i}) = log\Big(\frac{p_{i}}{1 - p_{i}}\Big) = \alpha + \beta _{1} x_{1} + \cdots + \beta _{n} x_{n}
\]</span></p>
<p>Thus, although the observed outcome variable is a dichotomic variable, the logistic regression estimates the <strong>log-odds</strong>, as a continuous variable, that the outcome variable is in a certain state (in our case, that the individual is a man)<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>. This model can be written as follows, where <span class="math inline">\(p_{i}\)</span> is the probability that an individual is a man.</p>
<p><span class="math display">\[
\begin{aligned}
\text{gender}_{i} &amp;\sim \mathrm{Binomial}(1, p_{i}) \\
logit(p_{i}) &amp;= \alpha + \beta \cdot \text{height}_{i} \\
\end{aligned}
\]</span></p>
<p>This model is implemented easily in R using the <code>glm</code> function, where the <code>family</code> argument is used to specify the likelihood of the model, and the link function.</p>
<pre class="r"><code>(mod2 &lt;- glm(male ~ height, data = d, family = binomial(link = &quot;logit&quot;) ) )</code></pre>
<pre><code>## 
## Call:  glm(formula = male ~ height, family = binomial(link = &quot;logit&quot;), 
##     data = d)
## 
## Coefficients:
## (Intercept)       height  
##    -53.3653       0.3438  
## 
## Degrees of Freedom: 351 Total (i.e. Null);  350 Residual
## Null Deviance:       486.6 
## Residual Deviance: 258.7     AIC: 262.7</code></pre>
<p>Below we print predictions of the model, using both the <code>predict</code> and <code>fitted</code> functions.</p>
<pre class="r"><code>d &lt;- d %&gt;%
  mutate(
    pred_mod2 = predict(mod2),
    fitted_mod2 = fitted(mod2)
    )

d %&gt;%
  select(height, weight, male, pred_mod2, fitted_mod2) %&gt;%
  head</code></pre>
<pre><code>##    height   weight male  pred_mod2 fitted_mod2
## 1 151.765 47.82561    1 -1.1910139 0.233077651
## 2 139.700 36.48581    0 -5.3387584 0.004778882
## 3 136.525 31.86484    0 -6.4302701 0.001609421
## 4 156.845 53.04191    1  0.5554049 0.635388646
## 5 145.415 41.27687    0 -3.3740373 0.033116790
## 6 163.830 62.99259    1  2.9567306 0.950580634</code></pre>
<p>This time the results of <code>predict</code> and <code>fitted</code> appear to be quite different… We can plot the predictions of <code>mod2</code> following the same strategy as previously using <code>fitted</code>. The <code>logit_dotplot</code> function displays the prediction of the logit model along with the marginal distribution of height by gender (detailed code can be found <a href="https://github.com/lnalborczyk/lnalborczyk.github.io/blob/master/code/logit_dotplot.R">here</a> ).</p>
<pre class="r"><code>source(&quot;logit_dotplot.R&quot;)
logit_dotplot(d$height, d$male, xlab = &quot;height&quot;, ylab = &quot;p(male)&quot;)</code></pre>
<p><img src="/post/2018-01-20-glm_files/figure-html/logit_dotplot-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The output of the <code>predict</code> and <code>fitted</code> functions are different when we use a GLM because the <code>predict</code> function returns predictions of the model on the scale of the linear predictor (here in the log-odds scale), whereas the <code>fitted</code> function returns predictions on the scale of the response. To obtain the <em>fitted</em> values, we thus have to apply the inverse of the link function to the predicted values obtained with <code>predict</code>. In our case, this translates to the logistic transformation:</p>
<p><span class="math display">\[p = \exp(\alpha) / (1 + \exp(\alpha) )\]</span></p>
<p>Which, in R, gives:</p>
<pre class="r"><code>exp(coef(mod2) ) / (1 + exp(coef(mod2) ) )</code></pre>
<pre><code>##  (Intercept)       height 
## 6.664323e-24 5.851092e-01</code></pre>
<p>Which is equivalent to using the <code>plogis</code> function:</p>
<pre class="r"><code>plogis(coef(mod2) )</code></pre>
<pre><code>##  (Intercept)       height 
## 6.664323e-24 5.851092e-01</code></pre>
<p>Let’s compare our previous calls to the <code>predict</code> and <code>fitted</code> functions…</p>
<pre class="r"><code>d &lt;- d %&gt;%
  mutate(pred_mod2_2 = plogis(predict(mod2) %&gt;% as.numeric) )

d %&gt;%
  select(height, weight, male, pred_mod2, fitted_mod2, pred_mod2_2) %&gt;%
  head</code></pre>
<pre><code>##    height   weight male  pred_mod2 fitted_mod2 pred_mod2_2
## 1 151.765 47.82561    1 -1.1910139 0.233077651 0.233077651
## 2 139.700 36.48581    0 -5.3387584 0.004778882 0.004778882
## 3 136.525 31.86484    0 -6.4302701 0.001609421 0.001609421
## 4 156.845 53.04191    1  0.5554049 0.635388646 0.635388646
## 5 145.415 41.27687    0 -3.3740373 0.033116790 0.033116790
## 6 163.830 62.99259    1  2.9567306 0.950580634 0.950580634</code></pre>
<p>To sum up, the <code>fitted</code> function automatically applies the inverse transformation to provide prediction on the scales of the outcome. A similar behaviour can be obtained by using the <code>predict</code> function, and by specifying the scale in which we want to obtain predictions (e.g., in the scale of the response variable).</p>
<pre class="r"><code>d &lt;- d %&gt;%
  mutate(pred_mod2_3 = predict(mod2, type = &quot;response&quot;) )

d %&gt;%
  select(height, weight, male, pred_mod2, fitted_mod2, pred_mod2_2, pred_mod2_3) %&gt;%
  head</code></pre>
<pre><code>##    height   weight male  pred_mod2 fitted_mod2 pred_mod2_2 pred_mod2_3
## 1 151.765 47.82561    1 -1.1910139 0.233077651 0.233077651 0.233077651
## 2 139.700 36.48581    0 -5.3387584 0.004778882 0.004778882 0.004778882
## 3 136.525 31.86484    0 -6.4302701 0.001609421 0.001609421 0.001609421
## 4 156.845 53.04191    1  0.5554049 0.635388646 0.635388646 0.635388646
## 5 145.415 41.27687    0 -3.3740373 0.033116790 0.033116790 0.033116790
## 6 163.830 62.99259    1  2.9567306 0.950580634 0.950580634 0.950580634</code></pre>
<p>To relate this to our understanding of the linear model equation, prediction pertains to the <span class="math inline">\(\mu_{i}\)</span>, meaning that we try to predict the mean observed outcome for a specific value of the predictor <span class="math inline">\(x_{i}\)</span>.</p>
<p>We should go further and implement uncertainty in these predictions, but we should first take a break to examine the concepts of errors and residuals, and their relationship.</p>
</div>
<div id="errors-and-residuals-the-residuals-function" class="section level2">
<h2>Errors and residuals: the <code>residuals</code> function</h2>
<p>A very common fallacy about the assumptions of the linear (Gaussian) model is that the <em>outcome variable</em> should be normally distributed. Instead, this assumption concerns the distribution of the outcome variable <strong>around its predicted value</strong> (i.e., the distribution of the errors).</p>
<p>What we actually said above is that the errors <span class="math inline">\(\epsilon_{i}\)</span> should be normally distributed around the predicted value. But the errors are the the non-observed (and non-observable) differences between the theoretical predicted value <span class="math inline">\(\mu\)</span> and the observed outcomes. Consequently, we do not have access to it. Instead, what we can work with are the residuals <span class="math inline">\(e_{i}\)</span>, which can be seen as an estimate (from the sample) of the errors <span class="math inline">\(\epsilon_{i}\)</span>, in a similar way as <span class="math inline">\(b\)</span> is an estimate of <span class="math inline">\(\beta\)</span>. To sum up, the residuals are the <span class="math inline">\(e_{i} = y_{i} - \bar{X}\)</span> whereas the errors are the <span class="math inline">\(\epsilon_{i} = y_{i} - \mu_{i}\)</span>.</p>
<p>In other words, errors pertain to the data generation process, whereas residuals are the difference between the model’s estimation and the observed outcomes. Basically, the residuals are the difference between the observed value and the predicted value. We can obtain them easily using the <code>residuals</code> function (which is useful for more complex models), or by subtracting to each observed outcome <span class="math inline">\(y_{i}\)</span> the predicted <span class="math inline">\(\mu_{i}\)</span>.</p>
<pre class="r"><code>d &lt;- d %&gt;%
  mutate(
    res1 = residuals(mod1),
    res2 = height - pred_mod1
    )

d %&gt;%
  select(height, weight, male, pred_mod1, res1, res2) %&gt;%
  head</code></pre>
<pre><code>##    height   weight male pred_mod1      res1      res2
## 1 151.765 47.82561    1  157.1630 -5.397960 -5.397960
## 2 139.700 36.48581    0  146.9001 -7.200111 -7.200111
## 3 136.525 31.86484    0  142.7180 -6.193000 -6.193000
## 4 156.845 53.04191    1  161.8839 -5.038870 -5.038870
## 5 145.415 41.27687    0  151.2362 -5.821164 -5.821164
## 6 163.830 62.99259    1  170.8895 -7.059520 -7.059520</code></pre>
<p>Below we plot these residuals, and make the alpha (i.e., the transparency) and the size of the points dependent on the distance to the predicted value (so that larger residuals appear as bigger and less transparent). This distance is also represented by the length of the vertical lines.</p>
<pre class="r"><code>d %&gt;%
  sample_frac(0.5) %&gt;% # selecting a (50%) subsample of the data
  ggplot(aes(x = weight, y = height) ) +
  geom_line(aes(y = pred_mod1), size = 1) +
  geom_point(aes(alpha = abs(res1), size = abs(res1) ) ) +
  guides(alpha = FALSE, size = FALSE) +
  geom_segment(aes(xend = weight, yend = pred_mod1, alpha = abs(res1) ) ) +
  theme_bw(base_size = 12)</code></pre>
<p><img src="/post/2018-01-20-glm_files/figure-html/abs-residuals-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>If we take all the above verticals bars (i.e., the residuals) and plot their distribution, we can compare them to a normal distribution with mean 0, and standard deviation <span class="math inline">\(\sigma\)</span> equal to the standard deviation of the residuals, to check our assumption about the distribution of the residuals (here a normality assumption).</p>
<pre class="r"><code>d %&gt;%
  ggplot(aes(x = res1) ) +
  geom_histogram(aes(y = ..density..), bins = 20, alpha = 0.6) +
  geom_line(aes(y = dnorm(res1, mean = 0, sd = sd(res1) ) ), size = 1) +
  guides(fill = FALSE) +
  theme_bw(base_size = 12) +
  labs(x = &quot;Residuals&quot;, y = &quot;Density&quot;)</code></pre>
<p><img src="/post/2018-01-20-glm_files/figure-html/distribution-residuals-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>To sum up, the distributional assumption of the linear model (Gaussian or whatever) concerns the distribution of the errors, that we do not know. Instead, we can evaluate the distribution of the residuals, which are the observed differences between the outcome variable and the predictions of the model.</p>
</div>
<div id="prediction-uncertainty-the-simulate-function" class="section level2">
<h2>Prediction uncertainty: the <code>simulate</code> function</h2>
<p>Recall that our model is:</p>
<p><span class="math display">\[
\begin{aligned}
\text{height}_{i} &amp;\sim \mathrm{Normal}(\mu_{i}, \sigma) \\
\mu_{i} &amp;= \alpha + \beta \cdot \text{weight}_{i} \\
\end{aligned}
\]</span></p>
<p>So far, we used the linear part of the linear model (i.e., the second line) to make predictions about the <span class="math inline">\(\mu_{i}\)</span>, from <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span>. In other words, we made predictions about mean values of the Gaussian distribution for a specific value of <code>weight</code>.</p>
<p>Now, if we want to generate actual data (i.e., the <span class="math inline">\(y_{i}\)</span>), from our model, we still have to include <span class="math inline">\(\sigma\)</span>. This can be done “by-hand”, by adding error (i.e., some random variation) to our predictions.</p>
<pre class="r"><code>d &lt;- d %&gt;%
  mutate(
    sim1 = coef(mod1)[1] + coef(mod1)[2] * d$weight + rnorm(1, 0, sigma(mod1) )
    )

d %&gt;%
  select(height, weight, male, pred_mod1, sim1) %&gt;%
  head</code></pre>
<pre><code>##    height   weight male pred_mod1     sim1
## 1 151.765 47.82561    1  157.1630 162.2150
## 2 139.700 36.48581    0  146.9001 151.9521
## 3 136.525 31.86484    0  142.7180 147.7700
## 4 156.845 53.04191    1  161.8839 166.9359
## 5 145.415 41.27687    0  151.2362 156.2882
## 6 163.830 62.99259    1  170.8895 175.9415</code></pre>
<p>The <code>simulate</code> function allows to automate the previous step and to run it <code>nsims</code> times.</p>
<pre class="r"><code>nsims &lt;- 1e4
sims &lt;- simulate(mod1, nsim = nsims) %&gt;% data.frame

sims[1:6, 1:6]</code></pre>
<pre><code>##      sim_1    sim_2    sim_3    sim_4    sim_5    sim_6
## 1 155.9598 155.3906 156.7651 152.7330 153.6077 156.5931
## 2 146.8243 141.4573 135.7357 153.7677 142.5962 150.1732
## 3 137.6233 141.3779 143.2266 149.4296 149.9607 144.1135
## 4 173.9980 162.2460 170.4402 157.2107 158.7464 159.1776
## 5 150.3885 156.8790 152.9237 140.2885 156.0903 144.1566
## 6 178.6628 166.6504 162.7225 167.7171 173.9149 179.0282</code></pre>
<pre class="r"><code>lower_ci_sim &lt;- apply(sims, 1, function(x) quantile(x, probs = 0.025) )
upper_ci_sim &lt;- apply(sims, 1, function(x) quantile(x, probs = 0.975) )

sims_summary &lt;- data.frame(
  lower = lower_ci_sim,
  upper = upper_ci_sim
  )

d %&gt;%
  ggplot(aes(x = weight, y = height) ) +
  geom_smooth(method = &quot;lm&quot;, color = &quot;black&quot;) +
  geom_point(size = 2, alpha = 0.3) +
  geom_ribbon(
    data = sims_summary, inherit.aes = FALSE,
    aes(x = d$weight, ymin = lower, ymax = upper), alpha = 0.1
    ) +
  theme_bw(base_size = 12)</code></pre>
<p><img src="/post/2018-01-20-glm_files/figure-html/simulate-ntimes-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The first shaded region around the regression line represents the 95% confidence interval around the regression line, whereas the second broader shaded area represents the 95% central quantiles of the Gaussian distribution at each value of weight. These are computed by simulating <code>nsims</code> height values at each weight value, and by taking the 95% mean values of this distribution.</p>
</div>
<div id="conclusions" class="section level2">
<h2>Conclusions</h2>
<p>In this post, we tried to shed light on some concepts of the generalised linear model by examining the similarities and differences between four common R functions. It should be acknowledged that these functions (<code>predict</code>, <code>fitted</code>, <code>residuals</code>, and <code>simulate</code>) work with many different types of models, including models fitted with <code>lme4</code> or <code>brms</code>. For instance, here is an overview of the available methods in my current session.</p>
<pre class="r"><code>methods(predict)</code></pre>
<pre><code>##  [1] predict.ar*                predict.Arima*            
##  [3] predict.arima0*            predict.brmsfit*          
##  [5] predict.bs*                predict.bSpline*          
##  [7] predict.glm                predict.glmmPQL*          
##  [9] predict.gls*               predict.gnls*             
## [11] predict.HoltWinters*       predict.lda*              
## [13] predict.lm                 predict.lme*              
## [15] predict.lmList*            predict.lmList4*          
## [17] predict.loess*             predict.lqs*              
## [19] predict.mca*               predict.merMod*           
## [21] predict.mlm*               predict.nbSpline*         
## [23] predict.nlme*              predict.nls*              
## [25] predict.npolySpline*       predict.ns*               
## [27] predict.pbSpline*          predict.polr*             
## [29] predict.poly*              predict.polySpline*       
## [31] predict.ppolySpline*       predict.ppr*              
## [33] predict.prcomp*            predict.princomp*         
## [35] predict.qda*               predict.rlm*              
## [37] predict.smooth.spline*     predict.smooth.spline.fit*
## [39] predict.StructTS*         
## see &#39;?methods&#39; for accessing help and source code</code></pre>
</div>
<div id="references" class="section level2">
<h2>References</h2>
<details>
<p><summary>Click to expand</summary></p>
<div markdown="1">
<p>Bürkner, P.-C. (2017). brms: An R package for bayesian multilevel models using Stan. Journal of Statistical Software, 80 (1), 1–28. <a href="doi:10.18637/jss.v080.i01" class="uri">doi:10.18637/jss.v080.i01</a></p>
<p>McElreath, R. (2016). Statistical Rethinking (p. 469). Chapman; Hall/CRC.</p>
<p>Rouder, J. N., Morey, R. D., &amp; Wagenmakers, E.-J. (2016). The Interplay between Subjectivity, Statistical Practice, and Psychological Science. Collabra, 2(1), 1–12. <a href="doi:10.1525/collabra.28" class="uri">doi:10.1525/collabra.28</a></p>
</div>
</details>
</div>
<div id="notes" class="section level2">
<h2>Notes</h2>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>For more details on the logit model, please check this <a href="http://www.barelysignificant.com/post/absenteeism/">previous post</a>.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>

    </div>

    



<div class="article-tags">
  
  <a class="badge badge-light" href="/tags/tutorial/">Tutorial</a>
  
  <a class="badge badge-light" href="/tags/r/">R</a>
  
  <a class="badge badge-light" href="/tags/glm/">GLM</a>
  
  <a class="badge badge-light" href="/tags/assumptions/">assumptions</a>
  
  <a class="badge badge-light" href="/tags/predict/">predict</a>
  
  <a class="badge badge-light" href="/tags/fitted/">fitted</a>
  
  <a class="badge badge-light" href="/tags/residuals/">residuals</a>
  
  <a class="badge badge-light" href="/tags/simulate/">simulate</a>
  
</div>



<div class="share-box" aria-hidden="true">
  <ul class="share">
    
      
      
      
        
      
      
      
      <li>
        <a href="https://twitter.com/intent/tweet?url=http://www.barelysignificant.com/post/glm/&amp;text=Using%20R%20to%20make%20sense%20of%20the%20generalised%20linear%20model" target="_blank" rel="noopener" class="share-btn-twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.facebook.com/sharer.php?u=http://www.barelysignificant.com/post/glm/&amp;t=Using%20R%20to%20make%20sense%20of%20the%20generalised%20linear%20model" target="_blank" rel="noopener" class="share-btn-facebook">
          <i class="fab fa-facebook"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="mailto:?subject=Using%20R%20to%20make%20sense%20of%20the%20generalised%20linear%20model&amp;body=http://www.barelysignificant.com/post/glm/" target="_blank" rel="noopener" class="share-btn-email">
          <i class="fas fa-envelope"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.linkedin.com/shareArticle?url=http://www.barelysignificant.com/post/glm/&amp;title=Using%20R%20to%20make%20sense%20of%20the%20generalised%20linear%20model" target="_blank" rel="noopener" class="share-btn-linkedin">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://web.whatsapp.com/send?text=Using%20R%20to%20make%20sense%20of%20the%20generalised%20linear%20model%20http://www.barelysignificant.com/post/glm/" target="_blank" rel="noopener" class="share-btn-whatsapp">
          <i class="fab fa-whatsapp"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://service.weibo.com/share/share.php?url=http://www.barelysignificant.com/post/glm/&amp;title=Using%20R%20to%20make%20sense%20of%20the%20generalised%20linear%20model" target="_blank" rel="noopener" class="share-btn-weibo">
          <i class="fab fa-weibo"></i>
        </a>
      </li>
    
  </ul>
</div>












  
  





  
  
  
    
  
  
  
  <div class="media author-card content-widget-hr">
    
      
      <img class="avatar mr-3 avatar-circle" src="/authors/admin/avatar_hueeaeb0c1f8e0a8e455cffe30658aa100_974173_270x270_fill_q90_lanczos_center.jpeg" alt="Ladislas Nalborczyk">
    

    <div class="media-body">
      <h5 class="card-title"><a href="http://www.barelysignificant.com/">Ladislas Nalborczyk</a></h5>
      <h6 class="card-subtitle">Postdoctoral researcher</h6>
      <p class="card-text">My main research interests span cognitive science and include motor cognition, motor imagery, overt and covert speech production, computational and statistical modelling, machine learning, and deep learning.</p>
      <ul class="network-icon" aria-hidden="true">
  
    
    
    
      
    
    
    
    
    
    <li>
      <a href="mailto:ladislas.nalborczyk@gmail.com" >
        <i class="fas fa-envelope"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://twitter.com/lnalborczyk" target="_blank" rel="noopener">
        <i class="fab fa-twitter"></i>
      </a>
    </li>
  
    
    
    
    
    
    
    
      
    
    <li>
      <a href="https://scholar.google.com/citations?user=na-dkLYAAAAJ&amp;hl=en" target="_blank" rel="noopener">
        <i class="ai ai-google-scholar"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://github.com/lnalborczyk" target="_blank" rel="noopener">
        <i class="fab fa-github"></i>
      </a>
    </li>
  
    
    
    
    
    
    
    
      
    
    <li>
      <a href="https://orcid.org/0000-0002-7419-9855" target="_blank" rel="noopener">
        <i class="ai ai-orcid"></i>
      </a>
    </li>
  
    
    
    
    
    
    
    
      
    
    <li>
      <a href="https://osf.io/ba8xt" target="_blank" rel="noopener">
        <i class="ai ai-osf"></i>
      </a>
    </li>
  
    
    
    
    
    
    
    
      
    
    <li>
      <a href="https://publons.com/a/1319011/" target="_blank" rel="noopener">
        <i class="ai ai-publons"></i>
      </a>
    </li>
  
</ul>

    </div>
  </div>







<section id="comments">
  
    
<div id="disqus_thread"></div>
<script>
  let disqus_config = function () {
    
    
    
  };
  (function() {
    if (["localhost", "127.0.0.1"].indexOf(window.location.hostname) != -1) {
      document.getElementById('disqus_thread').innerHTML = 'Disqus comments not available by default when the website is previewed locally.';
      return;
    }
    var d = document, s = d.createElement('script'); s.async = true;
    s.src = 'https://' + "barely-significant" + '.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="https://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>


  
</section>






  
  
  <div class="article-widget content-widget-hr">
    <h3>Related</h3>
    <ul>
      
      <li><a href="/post/icc/">Three methods for computing the intra-class correlation in multilevel logistic regression</a></li>
      
      <li><a href="/post/absenteeism2/">Experimental absenteeism and logistic regression, part II</a></li>
      
      <li><a href="/post/absenteeism/">Experimental absenteeism and logistic regression, part I</a></li>
      
      <li><a href="/post/matchpoint/">On power and the &#39;match point situation&#39;</a></li>
      
    </ul>
  </div>
  



  </div>
</article>

      

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha256-yt2kYMy0w8AbtF89WXb2P1rfjcP/HTHLT7097U8Y5b8=" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/highlight.min.js" integrity="sha256-eOgo0OtLL4cdq7RdwRUiGKLX9XsIJ7nGhWEKbohmVAQ=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/languages/r.min.js"></script>
        
      

    

    
    
      <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBt0DGWQoLr5PaW_Vq8JfoT2W1zoOyOGTI"></script>
      
      <script src="https://cdnjs.cloudflare.com/ajax/libs/gmaps.js/0.4.25/gmaps.min.js" integrity="sha256-7vjlAeb8OaTrCXZkCNun9djzuB2owUsaO72kXaFDBJs=" crossorigin="anonymous"></script>
      
    

    
    
    <script>const code_highlighting = true;</script>
    

    
    
    <script>const isSiteThemeDark = false;</script>
    

    
    
    
    
    
    
    <script>
      const search_config = {"indexURI":"/index.json","minLength":1,"threshold":0.3};
      const i18n = {"no_results":"No results found","placeholder":"Search...","results":"results found"};
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks"
        };
    </script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    

    
    
    <script id="dsq-count-scr" src="https://barely-significant.disqus.com/count.js" async></script>
    

    
    
    
    
    
    
    
    
    
      
    
    
    
    
    <script src="/js/academic.min.37431be2d92d7fb0160054761ab79602.js"></script>

    






  
  
  <div class="container">
    <footer class="site-footer">
  

  <p class="powered-by">
    © 2017-2021, Ladislas Nalborczyk &middot; 

    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
    <span class="float-right" aria-hidden="true">
      <a href="#" class="back-to-top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
</footer>

  </div>
  

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
